name: list_wheel_scroll_view_nls
version: 0.0.4
description: A flutter project which add scroll direction to ListWheelScrollView allowing you to have horizontal ListWheelScroolView.
repository: https://github.com/JoDeveloper/list_wheel_scroll_view_nls
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter: null
